# Generated by Django 3.0.8 on 2020-10-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.TextField(verbose_name='cat_name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='prod_id')),
                ('prod_name', models.TextField(verbose_name='prod_name')),
                ('cat_name', models.TextField(verbose_name='cat_name')),
                ('sub_cat_name', models.TextField(verbose_name='sub_cat_name')),
                ('pic_name', models.TextField(verbose_name='pic_name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.TextField(verbose_name='sub_cat_name')),
                ('cat_name', models.TextField(verbose_name='cat_name')),
            ],
        ),
    ]
